#!/home/kai69/anaconda3/bin/python3
# SPDX-FileCopyrightText: 2025 KaiKeiyama
# SPDX-License-Identifier: BSD-3-Clause

import sys
import math

n, r = map(int, input().split())

p_count = math.perm(n, r)
print(f"{p_count}")

c_count = math.comb(n, r)
print(f"{c_count}")

