#!/home/kai69/anaconda3/bin/python3
#SPDX-FileCopyrightText: 2025 KaiKeiyama
#SPDX-License-Identifier: BSD-3-Clause

import sys
import math

def main():
    try:
        word = input()
        length = len(word)
        result = math.factorial(length)
        print(f"\n{length},{result}")
    except EOFError:
        pass

if __name__=="__main__":
    main()
